INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("macho","manly","spanish","virile","stud","testosterone");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("blackmail","crime","extortion","demand","money","letters");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("blow","wind","air","whistle","nose","kiss");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("eggnog","christmas","punch bowl","spiked","creamy","brandy");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("ebenezer scrooge","christmas carol","character","ghosts","tightwad","humbug!");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("recycle","use","bin","waste","cans","paper");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("detective","investigate","crime","clues","private eye","sherlock holmes");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("skyscraper","empire","tall","new york city","high-rise","building");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("llama","south america","alpaca","beast","burden","dalai");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("museum","art","paintings","exhibits","buildings","collection");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("eureka!","moment","discovery","found","know","revelation");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("lei","flowers","necklace","hawaii","greeting","aloha");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("vegan","meat","vegetarian","eat","fish","diet");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("flannel","shirt","nightgown","cloth","sheets","pajamas");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("wheelbarrow","load","gardener","rubbish","handles","carry");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("pez","candy","toy","dispenser","push down","collectible");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("fool","punk'd","april","idiot","trick","jerk");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("diamond","baseball","ring","carats","jewel","engagement");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("trendy","faddish","fashionable","stylish","vogue","chic");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("pastered","drunk","intoxicated","smashed","walls","ceiling");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("alias","fake","name","aka","i.d.","false");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("chip","chocolate","cookie","potato","poker","pentium");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("grand slam","homer","bases","loaded","4","runs");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("menu","restaurant","order","entrees","bill of fare","prices");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("midas touch","gold","legend","money","rich","easy");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("bunsen burner","heater","lab","experiment","gas","flame");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("funny bone","hit","elbom","body","arm","feeling");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("scavenger hunt","search","game","find","contest","objects");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("comma","punctuation","mark","period","rest","separate");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("pocket","watch","hand","pants","trousers","pool table");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("panda","bear","black & white","china","bamboo","zoo");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("minutes","60","seconds","hours","time","meeting");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("r.s.v.p.","invitation","answer","respond","party","coming");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("tiara","crown","jeweled","head","gown","miss universe");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("mounthwash","rinse","gargle","brush","teeth","breath");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("jackhammer","drill","break-up","pavement","construction","rock");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("pentagon","5","sides","office building","washington dc","defense");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("flip flops","sandals","thongs","toes","beach","politician");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("whisper","speak","softly","ear","sound","shout");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("merry-go-round","carousel","spin","horses","pole","up & down");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("dark horse","unexpected","winner","surprise","behind","chance");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("howdy","hi!","hello!","greeting","cowboy","doody");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("big ben","london","parliament","chime","clock","time");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("slip","pink","fired","freudian","mistake","lingerie");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("canvas","tent","sail","cloth","bag","sneakers");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("lie detector","test","police","yes","no","polygraph");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("laugh","funny","ha-ha","chuckle","giggle","lol");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("spit","saliva","rotisserie","drool","expectorate","mouth");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("steeple","church","spire","tower","bell","top");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("shower","bathroom","bridal","water","clean","april");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("red herring","diversion","decoy","curve ball","trick","fake out");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("semi","truck","colon","circle","conductor","automatic");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("banjo","music","dixieland","bluegrass","strings","strum");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("tooth fairy","bed","pillow","money","make believe","night");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("the brothers grim","fairy tales","german","siblings","authors","storytellers");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("cough drop","lorenge","sore","halls","throat","suck");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("copper","penny","pipes","metal","coin","lincoln");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("filling","tooth","cavity","dentist","cream","oreo");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("key","door","open","car","lock","piano");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("parking meter","car","curb","machine","slot","quarters");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("sphinx","huge","sculpture","pyramids","man","lion");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("puppet","strings","finger","marionette","wooden","pinocchio");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("guru","hindu","wise","spiritual","teacher","go-to-guy");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("thomas edison","light bulb","electric","inventor","phonograph","movies");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("adult","grown-up","mature","old","child","x-rated");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("tie-dye","t-shirt","hippie","pattern","psychadelic","colors");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("poison ivy","itch","plant","rash","scratch","leaves");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("toll booth","highway","pay","attendant","coins","ticket");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("dr. jekyll","mr. hyde","robert louis stevenson","split personality","good","evil");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("school bus","yellow","children","pick up","vehicle","kids");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("stool pigeon","whistle blower","snitch","tattletale","turn in","informer");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("roman colosseum","arena","italy","gladiators","nero","thumbs up");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("boa","snake","coil","constrictor","feathery","scarf");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("slush","snow","rain","weather","fund","puppie");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("wallpaper","paste","hang","roll","strip","paint");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("big ten","midwest","state","universities","group","compete");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("greeting card","hallmark","message","rhyme","occasion","drugstore");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("jet lag","air","tired","travel","time","adjust");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("headhunter","job","recruiter","find","cannibal","shrunken");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("jingle","bells","ring","sleigh","horse","song");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("poker","card","hand","texas hold'em","game","bet");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("paul revere","ride","warning","british","coming","revolution");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("seagul","bird","beach","ocean","wings","landfill");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("gargoyle","carved","buildings","grotesque","monsters","ornament");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("octopus","tentacles","ocean","arms","8","squid");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("daydream","think","sleep","fantasize","bored","mind");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("thong","underwear","skimpy","butt","bikini","bathing suit");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("fortune cookie","advice","message","chinese","restaurant","predict");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("jacks","game pieces","metal","points","rubber ball","pick-up");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("tiffany","jewels","store","fifth avenue","breakfast","lamp");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("pupil","student","classroom","school","eye","dilated");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("yak","ox","tibet","chat","blab","gab");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("lullaby","baby","sleep","cradle","sing","rock");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("scale","weigh","musical","do re mi","fish","richter");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("bazooka","rocket","launcher","war","bubblegum","comics");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("liberty bell","ring","crack","freedom","america","symbol");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("cameo","jewelry","carved","profile","small","role");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("credit","card","money","bank","visa","master");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("gap","generation","jeans","old navy","store","mall");
INSERT INTO taboo(title, taboo1, taboo2, taboo3, taboo4, taboo5) VALUES ("brown-nose","flatter","bootlick","boss","suck-up","yes-man");
